### ISSUE TITLE
locale

### ISSUE THREAD

**Issue by nizo-m** [ahmedoid/hijri_picker#1]
السلام عليكم,
شكرا عالمجهود استاذ احمد,
واجهتني مشكلة وحيدة اللي هي اللغة..
كيف اظهر التقويم باللغة العربية

`                                    locale: Locale('ar'),
`
لاتظهر التقويم بالعربي

**Comment by ahmedoid** [comment]
وعليكم السلام
اعمل على تحديث للاضافة
