### ISSUE TITLE
Dart 3

### ISSUE THREAD

**Issue by MahmoudMoGamal** [ahmedoid/hijri_picker#11]
I am experiencing an incompatibility with Dart 3. When I try to compile my code, I get the following error:

/F:/flutter/.pub-cache/hosted/pub.dev/hijri_picker-3.0.0/lib/hijri_picker.dart:793:33: Error: The getter 'accentTextTheme' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/F:/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentTextTheme'.
          itemStyle = themeData.accentTextTheme.bodyText1;
                                ^^^^^^^^^^^^^^^
/F:/flutter/.pub-cache/hosted/pub.dev/hijri_picker-3.0.0/lib/hijri_picker.dart:795:32: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/F:/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
              color: themeData.accentColor, shape: BoxShape.circle);
                               ^^^^^^^^^^^
/F:/flutter/.pub-cache/hosted/pub.dev/hijri_picker-3.0.0/lib/hijri_picker.dart:804:43: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/F:/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
              ?.copyWith(color: themeData.accentColor);
                                          ^^^^^^^^^^^
/F:/flutter/.pub-cache/hosted/pub.dev/hijri_picker-3.0.0/lib/hijri_picker.dart:946:45: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/F:/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
                ?.copyWith(color: themeData.accentColor

**Comment by msayed-net** [comment]
same here

**Comment by othman98shawgan** [comment]
Any updates?
