### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by sAlfaifi** [ahmedoid/hijri_picker#3]
![ff](https://user-images.githubusercontent.com/29888488/83211250-4931f100-a165-11ea-9132-0eb83640b573.png)
png…]()

![ff2](https://user-images.githubusercontent.com/29888488/83211386-a7f76a80-a165-11ea-9eb0-90d487c2ca1f.png)

As you can see there are several errors related to rendering issues

this happen when i'm using calendar inside scrollable widget
thank you.

**Comment by kw2019ltd** [comment]
same issue for me

![image](https://user-images.githubusercontent.com/47334522/84247722-22829b80-ab11-11ea-9c9a-fd2a193caae9.png)


pls fix it

**Comment by HetalGohil** [comment]
same overflow error..can you please solve it as soon as posible

**Comment by ahmedoid** [comment]
fixed  text overflow issue.
https://pub.dev/packages/hijri_picker
