### ISSUE TITLE
Dialog ui bug

### ISSUE THREAD

**Issue by cheekiat** [ahmedoid/hijri_picker#9]
<img width="414" alt="Screenshot 2021-10-08 at 10 57 46 AM" src="https://user-images.githubusercontent.com/19680026/136491309-77e550ad-38f8-4f74-8ba5-fd11618d4e26.png">

**Comment by zeinabzahran** [comment]
Did you fix it?

**Comment by theahmadjawad** [comment]
Any fixes?

**Comment by Eng-MohamedGadala** [comment]
Can you fix it .this bug only shows with English language

**Comment by Eng-MohamedGadala** [comment]
@ahmedoid

**Comment by MuhammadUsamaSiddiqui** [comment]
Created Pull Request #10 to fix this issue. @ahmedoid Kindly review and merge the pull request. Thanks
